python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/alt_sched/dec_sched.py  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/alt_sched
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/alt_sched/very_alt.py  --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/alt_sched
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/alt_sched/very_alt.py --rm5 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/alt_sched
