python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/ToO/targetoo.py --too_rate 1 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/ToO
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/ToO/targetoo.py --too_rate 10 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/ToO
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/ToO/targetoo.py --too_rate 50 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/ToO
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/ToO/targetoo.py --too_rate 100 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/ToO
