python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF/dither_ddf.py --perNight --maxDither 0.7 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF/dither_ddf.py --perNight --maxDither 0.23 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF/dither_ddf.py --perObs --maxDither 0.7 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF/dither_ddf.py --perObs --maxDither 0.23 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF/desc_ddf.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/DDF
