python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines/baselines.py --nexp 1 --noPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines/baselines.py --nexp 1 --mixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines/baselines.py --nexp 1 --mixedPairs --survey_duration 366 --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines/baselines.py --nexp 1  --nomixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines/baselines.py --nexp 2  --mixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines/baselines.py --nexp 2 --nomixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines/no_ddf_baselines.py --nomixedPairs --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs/baselines
